export const englishOverrides = [
  { id: 164581, english: `A Love Yet To Bloom` },
  { id: 110826, english: `A Workplace Where You Can't Help But Smile` },
  { id: 148311, english: `How Do I Get Together With My Childhood Friend?` },
  { id: 176100, english: `Becoming Her Lover For The Sake Of Love` },
  { id: 161772, english: `Convenient Semi-Friend` },
  { id: 151909, english: `I See You, Aizawa-san!` },
  { id: 156935, english: `Even the Introverted Gals Wanna Get Out There!` },
  { id: 114358, english: `Oogami-san And Cerberus!` },
  { id: 87449, english: `2DK, G Pen, Alarm Clock.` },
  { id: 149755, english: `Still Not Normal Today` },
  { id: 139014, english: `Take Responsibility For My Stomach!` },
  { id: 110530, english: `Even If It Was Just Once, I Regret It` },
  { id: 103845, english: `Useless Princessess` },
  { id: 183605, english: `A Yuri Story About How My Classmate Whose Only Good Trait Is Her Excessively Pretty Face Comes at Me Relentlessly` },
  { id: 138110, english: `Alcohol and Oni Girls` },
  { id: 133500, english: `My Favorite Idol Became My Little Sister` },
  { id: 140060, english: `My Best Friend Who I Love Fell Completely in Love With My Vtuber Self` },
  { id: 117639, english: `The Two Sides Of Seiyuu Radio` },
  { id: 130799, english: `The Girl Through The Viewfinder` },
  { id: 102813, english: `We Can't Draw Love` },
  { id: 103608, english: `The Lonely Monster And The Blind Girl` },
  { id: 114860, english: `Kamitsuki Academy` },
  { id: 181342, english: `MAIDes: Maid Attacks In Destiny @Comic` },
  { id: 105808, english: `Hero-san and Former General-san` },
  { id: 154008, english: `The Fed-Up Office Lady Wants to Serve the Villainess` },
  { id: 178107, english: `The Helpless Saint and the Powerless Princess` },
  { id: 151254, english: `Erio And The Electric Doll` },
  { id: 175415, english: `Wanna Skip School In The Infirmary?` },
  { id: 146682, english: `Contract Sisters` },
  { id: 136739, english: `A Lonely Female CEO Falls for A Lesbian Prostitute in Seconds` },
  { id: 134443, english: `My Younger Senpai` },
  { id: 152703, english: `I Won't Sleep With You For Free` },
  { id: 109056, english: `It's A Detached Relationship.` },
  { id: 181042, english: `Our Love Is Disgusting` },
  { id: 161477, english: `Destroy It All And Love Me In Hell` },
  { id: 166947, english: `How To Break A Triangle` },
  { id: 164970, english: `False Marigold` },
  { id: 69959, english: `The Bones Of An Invisible Person` },
  { id: 121550, english: `Even If You Become Meat` },
  { id: 112919, english: `Beni Tsubaki` },
  { id: 169154, english: `Normality And Monsters` },
  { id: 157512, english: `The Gardens Of Gehenna` },
  { id: 172437, english: `Uninvited Wife, With Child!` },
  { id: 177537, english: `The Main Duties Of The Vicepresident` },
  { id: 134562, english: `The story of you, me, and her` },
  { id: 173101, english: `I (I) Love (Love) You (You)` },
  { id: 115093, english: `A World Exists For You` },
  { id: 105344, english: `Do You Still Rely On MAGIC?` },
  { id: 116286, english: `A Girl Who Can't Speak Thinks "She Is Too Kind."` },
  { id: 140684, english: `The Demon Disappears Through a Lens` },
  { id: 183343, english: `Belladonna's Lover` },
  { id: 129835, english: `If It Rains Next Week` },
  { id: 174603, english: `This Is Not Heaven, But...` },
  { id: 179139, english: `The Role Of The Femme Fatale` },
  { id: 179296, english: `Am I About to Join a Kill-or-Be-Killed Love Triangle?` },
  { id: 184992, english: `Cat Day` },

]